# Generated by Django 2.2.6 on 2020-03-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100, verbose_name='Product Title')),
                ('p_description', models.TextField(max_length=500, verbose_name='Product Description')),
                ('p_status', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=2, verbose_name='Status')),
                ('p_offer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Price')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual Price')),
                ('p_offers', models.TextField(verbose_name='Other Offers')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='products/item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
