# Generated by Django 2.2.6 on 2020-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_image',
            field=models.ImageField(blank=True, upload_to='products/category'),
        ),
    ]
