# Generated by Django 2.2.6 on 2020-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_c_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='p_brand',
            field=models.CharField(default=1, max_length=50, verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
